#!/bin/sh
# Launch boundary contract: trusted absolute identities, closed environment,
# argv arrays only, PlainText rendering, no shell, no bytecode. Static checks
# plus one offline bridge run on an unreachable bus — never touches BlueZ,
# Bluetooth hardware, or the desktop.
set -eu

repo=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT HUP INT TERM

fail() {
  echo "$1" >&2
  exit 1
}

panel="$repo/Panel.qml"
service="$repo/Service.qml"
model="$repo/Model.js"
bridge="$repo/bridge/pixelbuds_bridge.py"
cache="$repo/bridge/casecache.py"

# --- No pbpctrl, no shell scripts, no generated files in the tree ---
! grep -rn 'pbpctrl' "$panel" "$service" "$model" "$repo/manifest.json" || fail "pbpctrl is still referenced at runtime"
[ ! -e "$repo/status.sh" ] || fail "status.sh must be gone"
[ ! -e "$repo/pbpctrl-locked.sh" ] || fail "pbpctrl-locked.sh must be gone"
if command -v git >/dev/null 2>&1 && git -C "$repo" rev-parse >/dev/null 2>&1; then
  ! git -C "$repo" ls-files | grep -E '(__pycache__|\.pyc$)' || fail "generated bytecode is tracked"
fi

# --- QML launch contract ---
for f in "$panel" "$service"; do
  grep -q 'clearEnvironment: true' "$f" || fail "$f missing clearEnvironment"
  grep -q 'function launchEnvironment()' "$f" || fail "$f missing launchEnvironment"
  grep -q 'PATH: root.trustedPath' "$f" || fail "$f missing closed PATH"
  ! grep -q 'execDetached' "$f" || fail "$f uses execDetached (no closed env)"
  ! grep -q 'Quickshell.env("PATH")' "$f" || fail "$f inherits ambient PATH"
  for needle in PYTHONPATH PYTHONHOME PYTHONINSPECT PYTHONSTARTUP LD_PRELOAD LD_LIBRARY_PATH LD_AUDIT PIXELBUDS_TRUSTED_PATH; do
    ! grep -q "$needle" "$f" || fail "$f forwards $needle"
  done
  for tool in sh bash timeout gdbus python3 wl-copy omarchy-shell env; do
    ! grep -q "\[\"$tool\"" "$f" || fail "$f launches $tool via ambient PATH"
  done
  ! grep -qE '"(/usr)?/bin/(ba)?sh"' "$f" || fail "$f spawns a shell"
  ! grep -q '"-c"' "$f" || fail "$f passes a command string"
done
grep -q 'readonly property string python3Bin: "/usr/bin/python3"' "$service" || fail "Service.qml missing /usr/bin/python3"
grep -q 'readonly property string gdbusBin: "/usr/bin/gdbus"' "$service" || fail "Service.qml missing /usr/bin/gdbus"
grep -q 'readonly property string omarchyShellBin: "/usr/bin/omarchy-shell"' "$panel" || fail "Panel.qml missing /usr/bin/omarchy-shell"
grep -q 'command: \[root.python3Bin, "-I", "-B", root.bridgePath\]' "$service" || fail "bridge must be launched as python3 -I -B"
grep -q 'splitMarker: ""' "$service" || fail "bridge stdout must be read as bounded chunks"
grep -q 'Model.splitLines' "$service" || fail "bridge stdout must pass the line ceiling"
grep -q 'function splitLines' "$model" || fail "Model.js missing bounded line splitter"
grep -q 'Model.sanitizeStatus' "$service" || fail "status must be sanitized in QML"
grep -q 'Model.sanitizeControls' "$service" || fail "controls must be sanitized in QML"
# Auto-pause is in-process MPRIS only; never an external media tool.
! grep -qE 'playerctl|dbus-send|busctl' "$service" "$panel" || fail "auto-pause must not spawn media tools"
grep -q 'import Quickshell.Services.Mpris' "$service" || fail "auto-pause must use Quickshell MPRIS"

# Every Text element is PlainText (device names are device-controlled).
for f in "$panel"; do
  texts=$(grep -c '^\s*Text {' "$f" || true)
  plain=$(grep -c 'textFormat: Text.PlainText' "$f" || true)
  [ "$texts" -le "$plain" ] || fail "$f has Text without textFormat: Text.PlainText ($texts Text, $plain PlainText)"
done

# --- Python helpers ---
for f in "$bridge" "$cache"; do
  case "$(head -n1 "$f")" in
    "#!/usr/bin/python3 -I") ;;
    *) fail "$f shebang must be isolated /usr/bin/python3 -I" ;;
  esac
done
for f in "$repo"/bridge/*.py; do
  ! grep -nE '^\s*(import|from) +(subprocess|urllib|http|requests|ctypes|pty)\b' "$f" || fail "$f imports a forbidden module"
  ! grep -nE 'os\.(system|popen|exec[lv]p?e?|spawn)|shell=True' "$f" || fail "$f spawns processes"
done
grep -q 'sys.dont_write_bytecode = True' "$bridge" || fail "bridge must not write bytecode"

# --- Offline run: shadowed PATH, unreachable bus, stdin closed ---
mkdir "$tmp/shadow" "$tmp/runtime" "$tmp/state"
chmod 700 "$tmp/runtime"
for name in python3 gdbus bluetoothctl sh; do
  printf '#!/bin/sh\necho SHADOWED\nexit 42\n' >"$tmp/shadow/$name"
  chmod +x "$tmp/shadow/$name"
done
out=$(env -i PATH="$tmp/shadow:/usr/bin:/bin" HOME="$tmp" XDG_RUNTIME_DIR="$tmp/runtime" \
  XDG_STATE_HOME="$tmp/state" DBUS_SYSTEM_BUS_ADDRESS="unix:path=$tmp/no-such-bus" \
  /usr/bin/python3 -I -B "$bridge" </dev/null 2>"$tmp/err") || true
! printf '%s\n' "$out" | grep -q SHADOWED || fail "bridge executed a PATH tool"
printf '%s\n' "$out" | head -n1 | grep -Fxq '{"type":"hello","v":1}' || fail "bridge did not greet: $out"
printf '%s\n' "$out" | tail -n1 | grep -q '"type":"bye"' || fail "bridge did not say bye on an unreachable bus: $out"
[ ! -e "$repo/bridge/__pycache__" ] || fail "bridge wrote __pycache__"

echo "launch boundary test passed"
